package com.example.lesson20

const val EXTRA_RESULT_TEXT_VIEW = "EXTRA_RESULT_TEXT_VIEW"
const val BROADCAST_ACTION_SHOW_ERROR = "HelperAsyncTask.BROADCAST_ACTION_SHOW_ERROR"

const val EXTRA_RESULT_PROGRESS_BAR = "EXTRA_RESULT_PROGRESS_BAR"
const val BROADCAST_ACTION_PROGRESS_BAR = "HelperAsyncTask.BROADCAST_ACTION_INVISIBLE_BAR"

const val EXTRA_RESULT_TOKEN = "EXTRA_RESULT_TOKEN"
const val BROADCAST_ACTION_TOKEN = "HelperAsyncTask.BROADCAST_ACTION_TOKEN"

const val TYPE_CONTENT = "application/json; charset=utf-8"

const val TAG_INTERRUPTED_EXCEPTION = "CommunicatingWithTask"
const val MESSAGE_INTERRUPTED_EXCEPTION = "Server request error"
const val MESSAGE_NO_INTERNET_EXCEPTION = "Sorry, no internet"

const val KEY_FOR_SEND_TOKEN_ACTIVITY = "KEY_FOR_SEND_TOKEN_ACTIVITY"
